# Generated by Django 4.2.13 on 2024-05-21 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Отдел')),
                ('slug', models.SlugField(editable=False, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('is_married', models.BooleanField(default=False, verbose_name='В браке')),
                ('salary', models.SmallIntegerField(verbose_name='Зарплата')),
                ('department', models.ForeignKey(default='Без отдела', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='journalist', to='journalists.department')),
            ],
            options={
                'verbose_name': 'Журналист',
                'verbose_name_plural': 'Журналисты',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
